---
title: "R bootcamp topics"
output:
  html_document:
      toc:  TRUE
      toc_depth: 4
      toc_float: TRUE
      number_section: FALSE
---

## Slow R: basic introduction to R

This module provides a deliberately slow introduction to R that assumes that you have little or no experience with R and have not worked extensively with other programming languages.

- [Slow R](talks/slow-r.html) (Rick Gilmore) | [Download](talks/slow-r.Rmd)

*Other resources*

- Kelly Black R tutorial: https://www.cyclismo.org/tutorial/R/index.html
- James LeBreton [R introduction](https://psu-psychology.github.io/r-bootcamp/talks/R-Workshop-James.nb.html) (from R Bootcamp 2017) | [Rmd source](https://github.com/psu-psychology/r-bootcamp/blob/master/docs/talks/R-Workshop-James.Rmd)

***

## R-eproducible Science

- [R-eproducible Psychological Science](talks/r-eproducible-science.html) (Rick Gilmore)| [Download Rmd](talks/r-eproducible-science.Rmd).

- [R Markdown example output](talks/bootcamp-survey.html) using our own survey data | [Download Rmd](talks/bootcamp-survey.Rmd)

- Complete APA format manuscript based on `papaja` using the survey data, both in the original R Markdown format [Download Rmd](talks/gilmore-hallquist-bootcamp-2018-papaja.Rmd) version and the final [PDF](talks/gilmore-hallquist-bootcamp-2018-papaja.Rmd) version.

***

## Data wrangling

- [Tidy data conceptual overview](talks/Hallquist_Data_Wrangling_2018.pptx) (Michael Hallquist)

- [tidyr and dplyr walkthrough](talks/dplyr_walkthrough_2018.html) (Michael Hallquist) | [Rmd](talks/dplyr_walkthrough_2018.Rmd)

### Joining datasets

- dplyr [joins tutorial](talks/joins_tutorial_bnj.html) (Ben Johnson) | [zip](zips/johnson_joins.zip) | [Rmd](talks/joins_tutorial_bnj.Rmd)

*Other resources*
- Methods to compute [row-wise statistics in dplyr](https://github.com/jennybc/row-oriented-workflows/blob/master/ex09_row-summaries.md)

***

## Data visualization

- Conceptual overview of [ggplot2 and graphics output](talks/Hallquist_ggplot2_overview.pptx)

- Alicia Vallorani [ggplot2 walkthrough](talks/ggplot2_tutorial_vallorani.html)

*Other resources*

- Jenny Bryan [ggplot2 tutorial](https://github.com/jennybc/ggplot2-tutorial) | [Download](https://github.com/jennybc/ggplot2-tutorial/archive/master.zip)
- [ggplot2 documentation](http://ggplot2.tidyverse.org/reference/)
- ggplot2 tutorial that provides useful guidance on detailed formatting: <https://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html>

***

## Best practices in R programming

- Setting up a Github repo as an R project | [Video](mov/rstudio-project-on-github.mp4)

- Using Github within RStudio | [Video](mov/edit-save-commit-push.mp4)

*Other resources*

- [Wickham R style guide](http://adv-r.had.co.nz/Style.html)

***

## Data Analyses in R

### Correlation and regression in R

- Basic [correlation and regression walkthrough](talks/correlation_regression.html) (Michael Hallquist) | [Rmd](talks/correlation_regression.Rmd)

*Other resources*

- Probing interactions using the [jtools package](https://cran.r-project.org/web/packages/jtools/vignettes/interactions.html)
- UCLA [R data analysis examples](https://stats.idre.ucla.edu/other/dae/) (with comparisons to other programs)
- A more math-oriented overview of [multiple regression in R](https://rpubs.com/aaronsc32/multiple-regression)

### ANOVA and categorical data

- Basic [ANOVA and categorical data walkthrough](talks/anova_categorical.html) (Michael Hallquist) | [Rmd](talks/anova_categorical.Rmd)

*Other resources*

- More about the [aov_ez function](http://singmann.org/anova-in-r-afex-may-be-the-solution-you-are-looking-for/)
- Post hoc contrasts in ANOVA using the [afex package](https://cran.r-project.org/web/packages/afex/vignettes/afex_anova_example.html)
- A more math-oriented overview of [Tukey HSD in R](https://rpubs.com/aaronsc32/post-hoc-analysis-tukey)
- [Multinomial regression](https://stats.idre.ucla.edu/r/dae/multinomial-logistic-regression/) walkthrough
- [Logistic regression](https://stats.idre.ucla.edu/r/dae/logit-regression/) walkthrough

### Exploratory factor analysis

- [Exploratory factor analysis tutorial](talks/IntroBasicEFA_2018_0815.html) (Nilam Ram) | [zip](zips/ram_efa.zip) | [Slides](talks/RBootcamp_IntroFactorAnalysis_2018_0816.pdf) | [Rmd](talks/IntroBasicEFA_2018_0815.Rmd) | [QuantDev link](https://quantdev.ssri.psu.edu/tutorials/intro-basic-exploratory-factor-analysis)

### Structural equation modeling

- Structural equation modeling in [lavaan tutorial](talks/lavaan_tutorial.html) | [zip](zips/hallquist_lavaan.zip) | [Rmd](talks/lavaan_tutorial.Rmd)

*Other resources*

- Alison Schreiber We R [lavaan walkthrough](https://quantdev.ssri.psu.edu/tutorials/structural-equation-modeling-r-using-lavaan)
- Michael Hallquist [PSY 597 SEM course in R](https://psu-psychology.github.io/psy-597-SEM/)
- [lavaan tutorial](http://lavaan.ugent.be/tutorial/index.html)

***

## Core programming skills in R

- [Solving data problems algorithmically](talks/thinking_about_data_problems.html) (Michael Hallquist) | [zip](zips/hallquist_algorithmic.zip)

- [Scaling up with functions](talks/scaling_up_Albohn.html) (Dan Albohn) | [Rmd](talks/scaling_up_Albohn.Rmd)

*Other Resources*

- [Making Multi-Argument Functions & Data Frames Purrr](https://amber.rbind.io/blog/2018/03/26/purrr_iterations/)

***

## Parallel computing and big data

- Michael Hallquist [introduction to parallel R](talks/parallel_r.html) | [zip](zips/hallquist_parallel.zip) | [Rmd](talks/parallel_r.Rmd)

- [Example of parallel computation](R/clock_MEG_lmer.R.txt) on large neuroimaging dataset using foreach package | [Download](R/clock_MEG_lmer.R)

- Example of [setting a progress bar in a parallel foreach loop](https://gist.github.com/michaelhallquist/530035827ba46d16900b9f5b0169fb45) | [Download the whole script](R/fitVoxelwiseARMA.R) (for context)

*Other parallel computing resources*

- R [parallel package documentation](https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf)
- R [doParallel package documentation](https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf)
- Matt Jones [Parallel R tutorial](https://nceas.github.io/oss-lessons/parallel-computing-in-r/parallel-computing-in-r.html)
- Jonathan Dursi 'Beyond Single Core' [tutorial](https://ljdursi.github.io/beyond-single-core-R)

*Other big data resources*

- Rstudio [webinar about big data](https://www.rstudio.com/resources/webinars/working-with-big-data-in-r/)
- Useful big data presentation: <http://www.columbia.edu/~sjm2186/EPIC_R/EPIC_R_BigData.pdf>
- Programming with big data in R (pbdr): <https://pbdr.org>